#!/usr/bin/env bash

# Usage:
#     ./flash <app name> [avrdude args...]
#
# Custom programmer device:
#     DEVICE=/dev/ttyXXX ./flash <app name> [avrdude args...]

tup

filename=apps/"$1".hex
if [[ ! -f $filename ]]; then
  echo "File does not exist: $filename"
  exit 1
fi
shift

echo "Flashing: $filename"

avrdude -v -p m328p -c arduino -P ${DEVICE:-/dev/ttyACM0} -U flash:w:"$filename":i "$@"
