#!/usr/bin/env bash

result=0

make -B build/pc/cpu_test_runner.elf build/pc/integration_test_runner.elf || exit 1
build/pc/cpu_test_runner.elf || result=$?
build/pc/integration_test_runner.elf || result=$?
(( $result == 0 )) || echo TEST FAILED
exit $result
