#!/usr/bin/env bash

result=0

make -B pc/cpu_test_runner.elf pc/integration_test_runner.elf || exit 1
./pc/cpu_test_runner.elf || result=$?
./pc/integration_test_runner.elf || result=$?
(( $result == 0 )) || echo TEST FAILED
exit $result
